### ISSUE TITLE
Contribute page - Add text entry fields to provide justification and additional information to questions

### ISSUE THREAD

**Issue by pzwsk** [GFDRR/open-risk-data-dashboard#10]
We suggest to add a text entry field for most of the questions in order to provide justification to the answer and / or also give useful info to the user.

Does the data exist? (*) 

Name of the agency or organization that collects the data

--

Is data in digital form? (*) 	Yes No

No additional text entry field needed

--

Is the data available online? (*) 	Yes No

--

Publicly available? (*) 	Yes No

--

Is the metadata and/or documentation available online? (*) 	Yes No

--

Available in bulk? (*) 	Yes No

No additional text entry field needed

--

Is the data machine- readable? (*) 	Yes No

In which formats? Text entry field (or better tags for different formats)

--

Is the data available <remove>for</remove> free of charge? (*) 	Yes No

No additional text entry field needed

--

Openly licensed? (*) 	Yes No

URL or name of the license

--

Is the data provided on a timely and up to date basis? (*)

Date of last update 

--

Source URL to the data and metadata (can add more than one)

**Comment by daniviga** [comment]
Done in the backend via #12

**Comment by nastasi-oq** [comment]
Issue closed by @daniviga but still available. I retry to close it.
