### ISSUE TITLE
New background picture on home

### ISSUE THREAD

**Issue by pzwsk** [GFDRR/open-risk-data-dashboard#100]
Some beta users find the the current picture too ominous and suggest to find another one. 

I suggest the following one, still with a volcano but not active and the city below showing exposed assets (license free).

cc @vdeparday @cgiovando 

![image](https://user-images.githubusercontent.com/2378439/34616485-b67f2676-f238-11e7-84a7-130f438e17d9.png)

Source : https://unsplash.com/photos/BM22q72Z2YU

**Comment by CIMAManuel** [comment]
New layout is online in dev.riskopendata.org and in www.riskopendata.org.
