### ISSUE TITLE
Why "Earthquake" hazard is not available for NEPAL?

### ISSUE THREAD

**Issue by pzwsk** [GFDRR/open-risk-data-dashboard#103]
See https://www.riskopendata.org/dataset_list.html?idcountry=NP&idcategory=0

In ThinkHazard! risk is medium so should be available http://www.thinkhazard.org/en/report/175-nepal

**Comment by pzwsk** [comment]
Any idea?

**Comment by nastasi-oq** [comment]
@pzwsk getting data from thinkhazard we retrieved (when we get them) this: 
`... {"hazardlevel": {"mnemonic": "no-data", "title": "No Data"}, "hazardtype": {"mnemonic": "EQ", "hazardtype": "Earthquake"}}, ... ` we could try again (tomorrow) and check if something is changed.

**Comment by nastasi-oq** [comment]
`dev` now has ThinkHazard data updated to 2018-03-02, with more than 100 new hazards evaluation across all the countries (branch https://github.com/GFDRR/open-risk-data-dashboard/tree/thinkhazard180302)

**Comment by pzwsk** [comment]
Good thanks

**Comment by pzwsk** [comment]
Issue is back, reopening https://index.opendri.org/dataset_list.html?idcountry=NP&idcategory=0

**Comment by nastasi-oq** [comment]
My message last message was not so clear, I apologize, only `dev` machine was updated and waiting a LGTM to proceed, **_close_** the issue, interrupt the process; now also production is updated.
Check it and close the issue if no other problems are found.

**Comment by pzwsk** [comment]
Thanks, now closing

**Comment by nastasi-oq** [comment]
@pzwsk "now" is now.
