### ISSUE TITLE
Countries Rank

### ISSUE THREAD

**Issue by CIMAManuel** [GFDRR/open-risk-data-dashboard#105]
The ideal solution would be to compute the rank value as a function of the active filters. We need to check if that would be an issue backend side. In case it is we will maintain the absolute rank. the filtered ran comes for free in the pages with the tables of countries as we are sorting them on the fly to compose the table based on the filters. At the moment we do not have the possibility to extract the score in the dataset list view.

**Comment by pzwsk** [comment]
Can you please give us an update on this issue?
Thanks

**Comment by nastasi-oq** [comment]
@pzwsk it will be possible but requires at least 8 of development hours because, for efficiency reasons, is better do it using postgresql functionalities directly.

**Comment by nastasi-oq** [comment]
@pzwsk @CIMAManuel  done.
