### ISSUE TITLE
Country details (dataset list)

### ISSUE THREAD

**Issue by CIMAManuel** [GFDRR/open-risk-data-dashboard#106]
In this mask we should go for a unique structure for available and missing data. The new definition of dataset submitted is not any more the dataset instance, but the dataset typologies that atlas have 1 dataset instance contributed to the dashboard. therefore in the country details table we need to visualise the dataset typologies both for the available datasets and for the missing ones (with their own flag). in the case of the available datasets we will visualise the data of the best dataset uploaded for that dataset typology in terms of score. as a further step if the user clicks on that dataset the full group of instances uploaded for that dataset is visualised.

The present version of the API are:
submitted:  'dataset/?country=' + idCountry + sCategoryFilter + sApplFilter
missing: 'scoring/' + idCountry + '?' + sCategoryFilter + sApplFilter,

**Comment by pzwsk** [comment]
Can you please give us an update on this issue?
Thanks

**Comment by nastasi-oq** [comment]
From my perspective it is done; @CIMAManuel please can you confirm it?
