### ISSUE TITLE
Countries list (table and Map)

### ISSUE THREAD

**Issue by CIMAManuel** [GFDRR/open-risk-data-dashboard#107]
The table with the countries list and score is in line with the philosophy explained before for the “submitted” datasets. it is necessary then to revise the data structure to obtain the values that need to be in the table: Dataset Submitted and Datasets fully open, that cam be filtered per hazard and category.
the ref doc is: https://docs.google.com/document/d/1xpEQE2FFoRTMpKq7ydzTMEM8CG0aB3UwTEvZCeQzl-c/edit?usp=sharing

API : ‘scoring_category/

**Comment by pzwsk** [comment]
Can you please give us on update on this issue?
Thanks

**Comment by nastasi-oq** [comment]
From my perspective it is done; @CIMAManuel please confirm it.
