### ISSUE TITLE
Align list of key datasets with latest clean version (V10)

### ISSUE THREAD

**Issue by pzwsk** [GFDRR/open-risk-data-dashboard#108]
The list of datasets currently available on http://riskopendata.org/ does not match with versions 9, in some cases descriptions do no match with datasets name, and some datasets are missing.

In addition, version 9 available as a Google Spreadsheet only, was not a clean version ready to be used.

Therefore a new clean version 10 has been created.
Please align http://riskopendata.org with new V10 available below. 

CSV files

Datasets:
https://github.com/GFDRR/open-risk-data-dashboard/blob/master/backend/contents/key_datasets/resilience-index-datasets-list-v10%20-%20Datasets.csv

Tags:
https://github.com/GFDRR/open-risk-data-dashboard/blob/master/backend/contents/key_datasets/resilience-index-datasets-list-v10%20-%20Tags.csv

Google Spreadsheet (open to comments only):
https://docs.google.com/spreadsheets/d/1nleOGJpnCIwTZyYn-rrDZZjZnbDNASGiobLMdovY1M4/edit?usp=sharing

**Comment by nastasi-oq** [comment]
@pzwsk issue:
 * in the previous version codes `EX_4`, `EX_6`, `HA_10`, `HA_11A`, `HA_16A`, `HA_7`, `HA_8`, `VU_1`, `VU_3`, `VU_4`, `VU_6`, `VU_7A` are at `International` level, and someone is already populated with datasets. 
Change level for KeyDatasets without data associated is trivial but what to do with those with International data already associated ? 
From the database: 
   
  | KeyDataset Code | Number of dataset Instances |  Level | 
  | --- | --- | --- |
  | EX_4 | 9 | International |
  | EX_6 | 14 | International |
  | HA_10 | 8 | International |
  | HA_11A | 0 | International |
  | HA_16A | 0 | International |
  | HA_7 | 0 | International |
  | HA_8 | 0 | International |
  | VU_1 | 0 | International |
  | VU_3 | 0 | International |
  | VU_4 | 1 | International |
  | VU_6 | 3 | International |
  | VU_7A | 0 | International |

**Comment by pzwsk** [comment]
Please go ahead an change level to national. I will then review entries.

**Comment by pzwsk** [comment]
Just please verify there is no national level dataset with same name already.

**Comment by nastasi-oq** [comment]
@pzwsk `dev` has an imported version of `production` database with the migration to v10 already applied, please check it.

**Comment by pzwsk** [comment]
Last modification would be to change category of datasets below from Hazard to Base data.

HA_4	Soil type
HA_2	Water bodies
HA_1	Watershed boundaries

Please see changes applied in Yellow in Gdoc https://docs.google.com/spreadsheets/d/1nleOGJpnCIwTZyYn-rrDZZjZnbDNASGiobLMdovY1M4/edit#gid=1296008118

**Comment by pzwsk** [comment]
Hi @nastasi-oq I still see 3 datasets above categorized as hazard https://dev.riskopendata.org/contribute.html

**Comment by pzwsk** [comment]
Thanks, now closing.
