### ISSUE TITLE
DownloadCSV() not working

### ISSUE THREAD

**Issue by pzwsk** [GFDRR/open-risk-data-dashboard#111]
The download of the entire database as a CSV does not function anymore on riskopendata.org or the new version on dev.riskopendata.org

**Comment by pzwsk** [comment]
Chrome: OK

FF 58: KO
Edge: KO (open a new page but nothing happens then)
IE 11: KO

**Comment by nastasi-oq** [comment]
@pzwsk , @CIMAManuel 
At least Firefox and Chrome on Linux and Edge on Windows download (without any previous authentication) landing directly to the API link www.riskopendata.org/api/datasets_dump

**Comment by pzwsk** [comment]
Thanks @nastasi-oq www.riskopendata.org/api/datasets_dump also works on my side on FF, Edge and IE on Windows.

Issue might be with the function calling the API?

**Comment by CIMAManuel** [comment]
Dowload function updated in DEV platform: i tested FF, Edge and Chrome and fine ok
