### ISSUE TITLE
Numbers on homepage are taking time to appear

### ISSUE THREAD

**Issue by pzwsk** [GFDRR/open-risk-data-dashboard#113]
The figures within the circles on the homepage are taking time to appear.

As discussed the workaround is to have a daily update of those figures offline and some cache to show those numbers instantly online.

**Comment by pzwsk** [comment]
Cc @vdeparday @nastasi-oq for info

**Comment by nastasi-oq** [comment]
@pzwsk @CIMAManuel  I created a new view to retrieve just the 3 information required for the home page `/stats` already working on dev installation.

**Comment by CIMAManuel** [comment]
I just update in dev the new API from Matteo, can you try, please?

**Comment by pzwsk** [comment]
Thanks, working.

**Comment by pzwsk** [comment]
Reopening. Will close when implemented on production.

**Comment by pzwsk** [comment]
Still not working on production but working fine on dev.

Scenario for any web browser (FF, Chrome, IE 11, Edge).

1. I completely clear my browsing data.
2. I open riskopendata.org > number does not appear on homepage, even if I wait or refresh.
3 I open dev.riskopendata.org > number appears.

**Comment by nastasi-oq** [comment]
True, 'www' make the difference.

**Comment by CIMAManuel** [comment]
For me is ok.
Thanks Matteo
