### ISSUE TITLE
Store dataset related scoring on DB.

### ISSUE THREAD

**Issue by nastasi-oq** [GFDRR/open-risk-data-dashboard#115]
@pzwsk to avoid to recalculate each time the score of each dataset we introduced 2 new fields where are stored and recalculated at **insert** and **modify time** "basic" score and "thinkhazard normalized" score.
If the algorithm to calculate them changes a complete recalculation for all datasets is need.
To perform it a new `/scoring_update` BE view is added and accessible for `admin` users from FE admin panel.

**Comment by pzwsk** [comment]
Hi @CIMAManuel can you please indicate where to find this button on admin panel. Thanks

**Comment by CIMAManuel** [comment]
I added a button in submit page for admin user only (you'll see a tab "Scoring update")

**Comment by pzwsk** [comment]
Perfect, thanks
