### ISSUE TITLE
Number of datasets shown on /dataset_list.html and /countries.html

### ISSUE THREAD

**Issue by pzwsk** [GFDRR/open-risk-data-dashboard#120]
/dataset_list.html and /countries.html pages should consider highest score per datasets only for calculating : 

- Number of datasets considered
- Datasets
- Open

Otherwise, there is a lack of coherence with score which is calculated only based on highest scores.

For instance, below the number of datasets considered should be **36** (no filter).
Datasets should be **12**
Open should be **9**

![image](https://user-images.githubusercontent.com/2378439/36987360-67bc9af4-209c-11e8-99b9-0243c569272e.png)

**Comment by nastasi-oq** [comment]
I have already implemented it on a different branch and works as you asked.
A note: counters grouped by category and by perils MUST continue to work on datasets instances for for the database relations schema.
@pzwsk tell me if you want to activate it on `dev`.

**Comment by pzwsk** [comment]
Great, many thanks, can you just clarify " A note: counters grouped by
category and by perils MUST continue to work on datasets instances for for
the database relations schema. "

Otherwise, please activate on dev, yes.

Also, is there any way to retrieve number of key datasets applicable for
one hazard or one category?
This is for number of datasets considered on /countries.html

**Comment by pzwsk** [comment]
![image](https://user-images.githubusercontent.com/2378439/37041401-6d6a0ff2-215c-11e8-9ba3-fd9d10e9870b.png)

Hi @CIMAManuel, can you have a look and implement on countries.html?
Thanks

**Comment by pzwsk** [comment]
Getting back to this, seems to work fine on dataset_list however not working on countries page.

Showing 0 for both.

Best

**Comment by nastasi-oq** [comment]
Investigating.

**Comment by nastasi-oq** [comment]
Just a typo, fixed.

**Comment by CIMAManuel** [comment]
Page countries.html updated with the new value (keydatasets_count).

**Comment by pzwsk** [comment]
Thanks, closing.
