### ISSUE TITLE
Available in bulk?

### ISSUE THREAD

**Issue by pzwsk** [GFDRR/open-risk-data-dashboard#121]
I changed questions in ordd_api\models.py and frontend\js\angular\service.js but it is still not applied on dev.riskopendata.org

For instance the question "Available in bulk?" should now be "Is the data available in bulk?"

**Comment by nastasi-oq** [comment]
More in general: we haven't an automatic procedure to update `dev` or `production` sites.
In this specific case, on backend site, steps are:
-  refresh git on the server
- create a migration to update database
- apply the new migration

**Comment by pzwsk** [comment]
It's also up-to-date on my local instance, which is the same as on Git master.

@CIMAManuel can you please update FE on dev and production server ?
Thanks

**Comment by nastasi-oq** [comment]
@pzwsk Update FE on production imply a BE alignment that must be agreed.
Please move and stabilize `dev` installation to the next production candidate and just after freeze and test update `production`.

**Comment by CIMAManuel** [comment]
Question descriptions are in service.js file, i updated "bulk" question. Can you check please? If you have other questions to update let me know. Thanks

**Comment by pzwsk** [comment]
Ok thanks, I am closing this one.

**Comment by pzwsk** [comment]
Sorry, re-opening, can you please modify:

Is data in digital form? >
