### ISSUE TITLE
XX % open data on homepage

### ISSUE THREAD

**Issue by pzwsk** [GFDRR/open-risk-data-dashboard#124]
First feedback on homepage indicates that people rightly assume that the XX % open data figure is about the number of datasets fully open, not the average of datasets' score as it is currently calculated.

Would it be possible to return the percentage of datasets fully open (score 100%) rather than the average of datasets score?

Thanks

**Comment by nastasi-oq** [comment]
@pzwsk currently the number showed is:

(number_of_fully_opened / number_of_all_dataset_items) / 100.0

That seems what you already are asking for.

**Comment by pzwsk** [comment]
Ok, perfect then.
I am closing the issue.
