### ISSUE TITLE
[URGENT] Unable to save the dataset data

### ISSUE THREAD

**Issue by pzwsk** [GFDRR/open-risk-data-dashboard#125]
Scenario:
Sign In
Go to https://www.riskopendata.org/contribute.html?ctr=FR&ds=Administrative%20boundaries#dataset
Fill in the form
Click on "Submit a dataset"

Error message:

> Unable to save the dataset data: ValueError at /api/profile/dataset/ "" needs to have a value for field "id" before this many-to-many relationship can be used.

Error message detail: https://www.paste.org/91722

**Comment by nastasi-oq** [comment]
Looking what is passed to backend using the network developer tool of browser I see:
`<HOSTNAME>/api/keydataset/0/1/undefined/undefined` that seems some wrong composition of the FE, @CIMAManuel  could you check, please?

**Comment by CIMAManuel** [comment]
When i try to save (Submit dataset click) i have this error message: "Unable to save the dataset data: ValueError at /api-dev/profile/dataset/ "" needs to have a value for field "id" before this many-to-many relationship can be used. Request Method: POST Request URL: http://dev.riskopendata.org/api-dev/profile/dataset/".
Has there been any change on this API?

**Comment by nastasi-oq** [comment]
Problem seems to be in BE scope, investigating.
