### ISSUE TITLE
Issue with country score

### ISSUE THREAD

**Issue by pzwsk** [GFDRR/open-risk-data-dashboard#127]
There is an issue with country score calculation. For instance, France with only one dataset (base data, fully open) has a total score of 25%. 

See also country score filtered by base_data category.

![image](https://user-images.githubusercontent.com/2378439/37279802-238432fc-25ec-11e8-88b8-7486a94de9da.png)

**Comment by pzwsk** [comment]
FYI, I added 6 datasets for France today (some fully open, some not) but country score remains the same: 25%

https://www.riskopendata.org/dataset_list.html?idcountry=FR&idcategory=0

**Comment by nastasi-oq** [comment]
@pzwsk the current scoring algorithm is:
∀ Nation:
&nbsp;&nbsp;score = weighted average (see 4.3) ( ∀ category:
&nbsp;&nbsp;&nbsp;&nbsp;max_score( ∀ keydataset:
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;max_score( ∀ instance:
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;calculate score(see 4.1) * len((keydataset.applicabilty ⋃ instance.tag) ⋂ Nation.applicability) / 
        len(Nation.applicability)
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;)
&nbsp;&nbsp;&nbsp;&nbsp;)
&nbsp;&nbsp;)

In your specific case you have **ONLY** 7 datasets for France:

| score | normalized score (ThinkHazard) | keydataset.code | category.name | dataset.name |
| -----:| -------------:|-----------------|:------------------------:|-------------------------|
| 1.0 | 1.0 | BA_2A | Base data | Aerial imagery |
| 0.55 | 0.55 | BA_4 | Base data | Topographic map |
| 0.55 | 0.55 | BA_1A | Base data | Digital elevation model |
| 1.0 | 1.0 | BA_3 | Base data | Administrative boundaries |
| 1.0 | 0.2 | HA_2 | Base data | Water bodies |
| 0.9 | 0.18 | BA_5 | Base data | Bathymetry |
| 0.4 | 0.24 | HA_4 | Base data | Soil type |

Where you have **1.00** for some of them BUT doing the weighted average for all the categories:

 | Name | Weight |
|------|:------:|
| Hazard | 20 |
| Exposure | 20 |
| Vulnerability | 20 |
| Risk | 15 |
| Base data | 25 |

You obtain **(1.00 * 25) / 100** => **0.25** => **25%**
To test it try to add something different than "Base data" (that it is already at it's maximum) and see what happens.
Please, after you check update the bug or close it.

**Comment by pzwsk** [comment]
Many thanks Matteo for the details,

so issue #89 has not been addressed right ?

After internal review in December, we discussed and agreed on a much more
simple way for calculating score as people were quite confused about the
current methodology.

It is summarized here
https://docs.google.com/document/d/1xpEQE2FFoRTMpKq7ydzTMEM8CG0aB3UwTEvZCeQzl-c/edit#heading=h.v2y9qogpe8qt

Let's plan a call to discuss this.

Best
Pierre

**Comment by nastasi-oq** [comment]
> Many thanks Matteo for the details,
YW
> 
> so issue #89 has not been addressed right ?
As already told simplify scoring require a reasonable stability for all the rest of the code base during the development because it isn't trivial to avoid noise during debugging.

I still have to evaluate the effort to do it.

Except for that we remain that the Iissue #89 was blocked by WB internal discussion (tagging as blocked ... do you remember).

> --- 8< --- 8< --- 8< --- 8< --- 8< --- 8< --- 8< --- 8< --- 8< --- 8< --- 8< ---

**Comment by pzwsk** [comment]
Ok, I am going now to write clear specifications so that there is no
confusion regarding new country scoring formulas.
We can discuss then.

Best

**Comment by pzwsk** [comment]
Please see below, I tried to explain in plain english the new scoring methodology.

Country score is equal to the sum of all highest scores from datasets to be taken into account for that country divided by the number of datasets to be taken into account for that country.

In all cases, datasets to be taken into account for a country are datasets being "applicable for" or with "hazard tag" refering to at least one of the hazards whose level is medium or high on ThinkHazard! for that country.

When filtered by category, only datasets from that category are taken into account for country score.

When filtered by hazard, only datasets being "applicable for" or with "hazard tag" refering to the specified hazard are taken into account.

There is no more weight for categories.
There is no more normalized score (ThinkHazard) per dataset.

**Comment by pzwsk** [comment]
Note: might be good to discuss if still relevant to keep "applicable for hazard X" for key datasets or if it is possible to manage everything through tags and categories only.

**Comment by nastasi-oq** [comment]
> Please see below, I tried to explain in plain english the new scoring methodology.
> 
> Country score is equal to the sum of all highest scores from datasets to be taken into account for that country divided by the number of datasets to be taken into account for that country.

> highest scores from datasets

=> highest scores grouped by datasets names ?

> In all cases, datasets to be taken into account for a country are datasets being "applicable for" or with "hazard tag" refering to at least one of the hazards whose level is medium or high on ThinkHazard! for that country.

Ok.

> When filtered by category, only datasets from that category are taken into account for country score.
> 
> When filtered by hazard, only datasets being "applicable for" or with "hazard tag" refering to the specified hazard are taken into account.

Already in these ways.

> There is no more weight for categories.
> There is no more normalized score (ThinkHazard) per dataset.

Ok.

**Comment by pzwsk** [comment]
Yes, highest scores groups by datasets names.

Thanks

**Comment by pzwsk** [comment]
Hi, any feedback on this?

**Comment by nastasi-oq** [comment]
The new scoring algorithm description:
∀ nation ∈ Nation:
&nbsp;&nbsp;nation_score =  ∑ ( ∀ datasetname ∈ DatasetName:
&nbsp;&nbsp;&nbsp;&nbsp;max_score( { ∀ d ∈ Dataset(nation, datasetname): ((d.keydataset.applicabilty ⋃ d.instance.tag) ⋂ nation.applicability)  ≠ Ø } )
&nbsp;&nbsp;) / len( DatasetName )

**Comment by pzwsk** [comment]
Thanks @nastasi-oq, 

one remaining issue in the formula though, divisor should change depending on the number of datasets to be taken into account.

This is the "Number of datasets considered" visible on https://dev.riskopendata.org/countries.html

For instance, if score is filtered by Base Data, divisor should be 8 not 36.

Dividend seems to be ok.

**Comment by nastasi-oq** [comment]
@pzwsk Implemented "number of datasets considered" instead of "total number of datasets" as normalization factor.
New version is already installed on `dev`.

**Comment by pzwsk** [comment]
Many thanks for reactivity.

Now looks OK to me for general country score and country score filtered by category and hazards.
