### ISSUE TITLE
Fix issues with new domain name index.opendri.org

### ISSUE THREAD

**Issue by pzwsk** [GFDRR/open-risk-data-dashboard#138]
Below are some of the functionalities not working with index.opendri.org as domain name. 
I guess most of the issues come from same settings to be changed with domain name. 

- [x] Numbers not showing up in circles on homepage
- [x] Sign in 
- [x] Explore locations (countries)

**Comment by daniviga** [comment]
Issues should have been resolved. The SSL certificate and the nginx configuration have been extended to support `index.opendri.org`.

**Comment by pzwsk** [comment]
Checked, thanks, closing this one.
