### ISSUE TITLE
Missing margin for title

### ISSUE THREAD

**Issue by cgiovando** [GFDRR/open-risk-data-dashboard#139]
On my screen (MBP, OSX 10.11, Chrome 66) the title spreads all the way to edge of the browser window. See screenshot below:

![screen shot 2018-05-10 at 10 42 32](https://user-images.githubusercontent.com/10201533/39860877-34e31050-543f-11e8-94fa-7d1bc98fa167.jpg)

**Comment by oncletom** [comment]
Hello @cgiovando,

Thanks for reporting the problem a few months ago and thanks for your patience 🙂 

We figured out a sensible change to do to ensure margins on this element. The same issue applied to the baseline as well 👍 The _yellow_ and _purple_ areas on the following screenshots highlight the newly added margin.

# Large screen

The title container has a maximum length.

<img width="1068" alt="image" src="https://user-images.githubusercontent.com/138627/45950966-0d46a000-c002-11e8-9736-ea412c891d7b.png">

# Small screen

The title is padded to prevent it to reach the side of the screen.

<img width="773" alt="image" src="https://user-images.githubusercontent.com/138627/45951049-5a2a7680-c002-11e8-85f2-b84f48eb46f6.png">


Let us know if that suits with your expectation, and we are working on deploying an updated version of the website during the week.
