### ISSUE TITLE
Two live URLs with different data

### ISSUE THREAD

**Issue by vdeparday** [GFDRR/open-risk-data-dashboard#143]
https://www.riskopendata.org/ is still live with data that seems to be different than the data on https://index.opendri.org/ 

So I think we should retire https://www.riskopendata.org/ or redirect it to the new one.

**Comment by daniviga** [comment]
I added a redirect on the old server the redirects visitors to the official https://index.opendri.org.
This is a temporary solution: if you want to keep the old domains (.org and .eu), a changed in their DNS zone should be performed instead (like `riskopendata.org -> CNAME -> index.opendri.org`).
The owner of `riskopendata.*` looks to be CIMA, so I think you should ask @CIMAManuel to make those changes.

**Comment by pzwsk** [comment]
Thanks, please remove riskopendata domain names, we will not use this address anymore. Thanks

**Comment by daniviga** [comment]
For now I configured the webserver to return a 404 for `*.riskopendata.org` and `*.riskopendata.eu`, this should help the search engines to 'forget' about them. I left active only `dev.riskopendata.org` to be used for the development website.

@CIMAManuel could you please remove all the DNS records for `riskopendata.org` and `riskopendata.eu` except for `dev.riskopendata.org`? I guess that `riskopendata.eu` can be removed at all. If you want to remove/not renew both, we can indeed use one of our institutional domains for the development instance.

**Comment by oncletom** [comment]
I guess this one can be closed.
