### ISSUE TITLE
Add a 404 not found page

### ISSUE THREAD

**Issue by pzwsk** [GFDRR/open-risk-data-dashboard#144]

**Comment by CIMAManuel** [comment]
Client side added a new html page in the root: error_404.html.
@daniviga can you implement server side redirect?
Thks

**Comment by daniviga** [comment]
@CIMAManuel done!

```nginx
error_page 404 /error_404.html;
```

Now the reverse proxy (Nginx) sends the content of `error_404.html` in case of a `404` response.

**Comment by pzwsk** [comment]
Ok looks good, thanks!
