### ISSUE TITLE
Not possible to submit data for Company register Albania

### ISSUE THREAD

**Issue by pzwsk** [GFDRR/open-risk-data-dashboard#146]
It has been reported that it was not possible to submit dataset for company register in Albania.

See screenshot
![image](https://user-images.githubusercontent.com/2378439/43639501-b5c463c0-971c-11e8-8699-e0328e77c777.png)

**Comment by nastasi-oq** [comment]
Selecting ``Albania`` => ``Exposure`` => ``Company register`` there is a misalignment between data retrieved from the server related to ``Company register`` and what the client is trying to save as new dataset instance, please @CIMAManuel could you verify it ?
![alb_shot](https://user-images.githubusercontent.com/1670278/43645902-91236f2c-9733-11e8-91e4-3b72df0db369.png)
![alb_shot2](https://user-images.githubusercontent.com/1670278/43645903-913e742a-9733-11e8-83cb-9e2334e5acc7.png)

**Comment by pzwsk** [comment]
Error message : 

`"Tag 'River flooding' not allowed for KeyDataset`

It seems client sent river flooding tag checked as yes whereas company register does not have this tag element.

**Comment by pzwsk** [comment]
And here is what the API request return for Company register: https://index.opendri.org/api/keydataset/0/3/44/EX_3D

`HTTP 200 OK
Allow: GET, HEAD, OPTIONS
Content-Type: application/json
Vary: Accept

[
    {
        "code": "EX_3D",
        "level": "National",
        "category": "Exposure",
        "dataset": {
            "id": 44,
            "name": "Company register",
            "category": null
        },
        "description": "List of registered companies for the country including their addresses and economic sector.",
        "tag_available": {
            "group": "time reference",
            "tags": []
        },
        "applicability": [
            "River flooding",
            "Coastal flooding",
            "Tsunami",
            "Cyclone",
            "Earthquake",
            "Volcano",
            "Landslide",
            "Water scarcity"
        ]
    }
]`

**Comment by pzwsk** [comment]
I might be wrong but it seems there is a mismatch between tag_available and applicability and client is using applicability instead of tag_available to send back to server. 

See an example where it is working https://index.opendri.org/api/keydataset/0/1/1/BA_1A

**Comment by CIMAManuel** [comment]
Issue resolved, I tested on dev platform but not in index.opendri.org, can you try with real data, please?
Thks

**Comment by nastasi-oq** [comment]
It works also on production (clean of browser cache is required).
for @CIMAManuel : after the successfully insert, click on "my dataset" tab doesn't show the just inserted dataset and you must perform a page reload to see it, could you force a "behind the scenes" reload of owned datasets to avoid this misleading behavior ?

**Comment by nastasi-oq** [comment]
@pzwsk **yes**

Explaination
----------------
currently we have this list of ``KeyTagGroup``:
```
building
facilities
hazard
time reference
```
**Time reference** has no ``KeyTag`` associated (the full list of KeyTags below).

The only ``KeyDataset`` associated with this ``KeyTagGroup`` is **Company register**.


This is the list of current ``KeyTag``  prefixed with their own ``KeyTagGroup``:
```
hazard - Earthquake
hazard - Cyclone
hazard - Tsunami
hazard - River flooding
hazard - Coastal flooding
hazard - Volcano
hazard - Water scarcity
hazard - Landslide
building - Count
building - Replacement value
building - Height
building - Material
building - Roof type
facilities - Power
facilities - Health
facilities - Education
facilities - Airports
facilities - Bridges
facilities - Railways
facilities - Roads
facilities - Harbors
facilities - Water
facilities - Telecommunication```

**Comment by nastasi-oq** [comment]
@pzwsk Analyzing the current DB content I found that the 6 KeyDatasets below hasn't a ``KeyTagGroup`` associated, is it correct ?
```
BA_3 Administrative boundaries
BA_4 Topographic map
EX_1 Land cover
EX_2A Population
EX_3A Economic activities
EX_5 Agricultural production
```

**Comment by pzwsk** [comment]
Yes, correct, and we will need to review this in next phase as we still have confusion on what is an element for users. But for now, closing this issue.
