### ISSUE TITLE
Improve Admin Dataset Review feature

### ISSUE THREAD

**Issue by pzwsk** [GFDRR/open-risk-data-dashboard#151]
See https://index.opendri.org/contribute.html#datasetreview

(need to be logged in as admin)

Columns should be:

- Location
- Dataset
- Open Data Criteria
- Submission date
- Review button

Thanks

**Comment by nastasi-oq** [comment]
Location is already returned in the request submitted to the REST API.

**Comment by pzwsk** [comment]
OK can we implement something quickly on FE, it does not have to be fancy
but currently it is difficult for us to conduct and plan reviews of
datasets as we don't have enough info.

Thanks

**Comment by CIMAManuel** [comment]
Yes, we can. I'll do it today, ok?

**Comment by pzwsk** [comment]
Great, thanks

**Comment by CIMAManuel** [comment]
Page modified. Clear your cache file before. 
Let me know!

**Comment by pzwsk** [comment]
Looks good. Thanks closing
