### ISSUE TITLE
Setup Netlify Deploy Key and Webhook on GitHub Repository

### ISSUE THREAD

**Issue by oncletom** [GFDRR/open-risk-data-dashboard#159]
@GFDRR, @pzwsk, @vdeparday, I'd like to setup netlify.com to build branch previews for the _frontend_ app of this repository. There are a few actions to take to enable this.

1. [x] **Deploy Key**
1. [x] **Webhook**

# Setup Deploy Key

1. Paste the deploy key on this page: https://github.com/GFDRR/open-risk-data-dashboard/settings/keys/new

```
`ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDW9LEaa7OypaqEf75wEmxwSOn2o7P3vLCFdq5pPIuUZLXhEBddP92ExnL/yFwIk0Ff97/su9LDdWKDc6tkcmTt5qa+c/aYE/JWjIx81bfQ5PpTeKKmkMn2DrnB9lmLwFI2aTtK5Rna8fRTYpmzo4oEd/OYrKTIb0JkmYpbqcen4TnYQRBCJ872mYH0b6HEZdDkTD1zwenvxo8UN4x07lGMUFfVkydhx35qKgcWpnTOUgPaOBtHGobI7+BqtpC3Z9rKUxnlD9Kg1VqWZ5LndidLWK/a1xDFwsb3pXpRzIYXYiWnz7EIIp0Y+F4zGGOPYT9YDZsbIvuOhL2qPTji4+ep`
```

2. Submit the form

# Setup Webhook

1. Go to https://github.com/GFDRR/open-risk-data-dashboard/settings and…:
   1. **Payload URL**: `https://api.netlify.com/hooks/5baa4126fdd72a3bd3f49f3b`
   1. **Content Type**: `application/json`
   1. Tick `Let me select individual events.` and…
      1. Tick `Pull Requests`
      1. Tick `Pushes`
1. Submit the form

Is that okay with you?

Thanks for your help,
Let me know if you need additional informations.

---

# Alternative

If you create a `@GFDRR/opendri-frontend` team with _Write access_ (maybe _Admin access_? I don't know if _Write_ is sufficient to make it work with Netlify and Travis - cf. #156), @dedandy, @CIMAManuel and I could manage these operations without bothering you.

Ideally, I'd like to be able to setup GitHub Projects to track the progress we make.

**Comment by pzwsk** [comment]
Done. Let me know if ok?

**Comment by oncletom** [comment]
Hello @pzwsk,

It worked perfectly but I did a mistake as I gave you the info related to _my fork_ of the repo.

Would it be possible to redo the steps with these informations instead:

## Deploy Key

```
ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDekhsV0h+uDpNBe/UFGAezg7VIT2eYZaxFUH3CrTzNkD0iHLvPYTWbec222VlKN48eugKkrf7fHIKWvw6xSUcDv10CFcX2ihkvFz7AFk+YOueLM4/aKT9TZpKk2c9THB4lm+p6/hoc4B8jPULG3tQoXJO1xjCLrbZkHijvFJ/3b2Lh/ZppCJEz9AEibulRO2c0VPigXnUA83a1yEXP9iNqQZ9OOl1m9jHu29/2iRNGyCm7HTMgnZMyV7aO64x16LsWM7n2WYsjiXzoEQmJxXHb/ZEuchNvZ87WDZZvy2tJioQaWHNaYKdB6f75rAzvOq2QjfHUH4OSWKhvvii995qB
```

## Webhook URL

Nothing to do.

Thank you and sorry for the annoyance.

**Comment by oncletom** [comment]
@pzwsk you asked me this morning if I was waiting for elements; ^ the comment above is something I am waiting for. It is a new deploy key to add to this repository, to complete the setup of the Preview tool.

**Comment by oncletom** [comment]
OK, I finished the setup thanks to #169 👍
