### ISSUE TITLE
Travis CI walkthrough

### ISSUE THREAD

**Issue by dedandy** [GFDRR/open-risk-data-dashboard#172]
Present a workflow where each commit pushed to the master branch are automatically deployed to dev.riskopendata.org.

**Comment by pzwsk** [comment]
Question: what would happen for deployment if we revert to a previous version?

**Comment by oncletom** [comment]
If you revert a commit (using `git revert` for example), the latest version of `master` will be deployed.

In all cases, the latest commit of `master` will be deployed.

**Comment by oncletom** [comment]
Will document how it works in #177
