### ISSUE TITLE
Improve registration email

### ISSUE THREAD

**Issue by pzwsk** [GFDRR/open-risk-data-dashboard#182]
The email received by a user to confirm his registration looks not very nice. See screenshot below.

I suggest the following:
* Sent by: currently, the email is sent by `manuel.cavallaro@cimafoundation.org` we need to change to a generic email `contact@index.opendri.org` (need to investigate what to do for that)
* Email object: change to `Confirm Registration to Open Data for Resilience Index`
* Content: remove pictures, logo, buttons, etc. in the content. Instead, only use text and hyperlinks.
* Suggested text: 

> Thanks for your request to register to the Open Data for Resilience Index.
> Please confirm your registration by clicking on the following url: http://..................
> You will then be able to submit datasets.

![image](https://user-images.githubusercontent.com/2378439/46334086-0253c700-c623-11e8-9923-67f015a1c51f.png)

**Comment by oncletom** [comment]
So if I understand well, you suggest the email to be sent as plain text, using the default email client font size and such, correct?

> the email (…) looks not very nice

If I were the person who put all my heart into designing the emails, I would not receive this bit very well.

**Comment by nastasi-oq** [comment]
Currently development site has 'manuel.cav...' as sender (for testing purpose I think), instead production site has 'noreply@index....'  if something not fit this scenario there is a bug.
If you want to change ``noreply`` with ``contact`` for production is just configuration thing.

**Comment by pzwsk** [comment]
@oncletom yes correct. I am suggesting this as a quick but efficient fix but we can discuss other solutions. "Not very nice" meaning: currently a user is welcomed with logo and an empty map and has to scroll down to see message and click on confirm button. We can do better in terms of UI/UX I think and in general I find plain text more efficient than many nice designed registration emails.  But again to be discussed.

**Comment by dedandy** [comment]
@pzwsk @oncletom  yes I'm agree about look now is not very nice with website.
Need try to improve ux/ui.
Sure a simple text will be ok for all platform instead html have some problem with gmail and other clients .... But I want try give a better look. Even a simple logo + text information  .... @oncletom if you have suggests about html/email form, and practice what to do or not (frontend) I get it! :)

**Comment by pzwsk** [comment]
Hi, what needs to be reviewed here?

**Comment by oncletom** [comment]
@pzwsk a proposal has been made in #243, alongside unrelated changes which made it hard to read, test and merge bit by bit. I suppose @dedandy is working on splitting the proposals in several pull requests to ease up the conversation.

**Comment by dedandy** [comment]
Yes now I'm splitting #243 in single proposal
