### ISSUE TITLE
Icons layout issue on dataset_list

### ISSUE THREAD

**Issue by pzwsk** [GFDRR/open-risk-data-dashboard#183]
Issue with alignment of dataset category icons on https://index.opendri.org/dataset_list.html. See below

See 
![image](https://user-images.githubusercontent.com/2378439/46334686-4c3dac80-c625-11e8-8970-af7897abc614.png)

**Comment by pzwsk** [comment]
As a quick fix, I would suggest to use similar layout of id="menu-hazard" (less divs inside) and order of icons as in Explore Locations page where there is no issue with large screens.

**Comment by oncletom** [comment]
The component has been refactored later down the line in a pull request I cannot find.
