### ISSUE TITLE
WORKSHOP: what are the pages goals?

### ISSUE THREAD

**Issue by oncletom** [GFDRR/open-risk-data-dashboard#191]
What are the questions/goals we want to answer for…
- the homepage
- the datasets list page
- for a country page
- key dataset page
- dataset detail page

**Comment by pzwsk** [comment]
Yes, I am going to send invite.

**Comment by pzwsk** [comment]
I would add key dataset and dataset detail page

**Comment by gracedoherty** [comment]
Homepage:

It's too busy, visually. The tagline ("Tracking open data...") is as large as a title yet behaves like a subtitle, with underlines and links. A title should not have links. If you go to the mobile site, this and the background image take up all the space and the reader's attention. It isn't intuitive to click on the bubbles ("469 datasets"). Compare this to the open data index, which is clean and straightforward.

As far as what we want it to do:
-The homepage should describe and provide links to all major aspects of the site, in a way that gives just enough information that the reader 1) understands what it's for and 2) wants to learn more or see examples.
-It should begin to tell the story of the need for an open data for resilience index, which links you to the About. Right now it offers a summary with links to more information, which isn't the same and isn't as likely to draw the user in.
-I should be able to search for the things I want, without having to follow the organization of the site. If I want to learn about the availability of tsunami data, I don't know yet that this requires going to the Explore Countries page and clicking on the icon. We need a general search bar.
