### ISSUE TITLE
Registration: some emails are considered invalid whereas they are valid

### ISSUE THREAD

**Issue by oncletom** [GFDRR/open-risk-data-dashboard#216]
<img width="648" alt="image" src="https://user-images.githubusercontent.com/138627/46655071-c84a6e00-cbaa-11e8-8673-279c82cb76d2.png">

`blah@entre-quote.com` does not work<br>
`blah@entrequote.com` works.

---

Also, email is displayed as invalid when the first character has been typed. It's a bit too soon.

**Comment by pzwsk** [comment]
Hi @CIMAManuel can you explain what has been done here so that we say OK or not?

Thanks

**Comment by CIMAManuel** [comment]
Hi @pzwsk, i wrote a little description in the pull request.
I changed the regex (roles) value of the function that check email format.
Please see here: https://github.com/GFDRR/open-risk-data-dashboard/pull/284

Thanks

**Comment by oncletom** [comment]
@CIMAManuel what I understand from @pzwsk is it's not clear what changed and why this is going to solve the problem.

To me, the fix addresses the problem although it might not prevent more exotic formats [compliant to the e-mail address specification](https://tools.ietf.org/html/rfc5322#section-3.4.1) ([a bit more readable on Wikipédia](https://en.wikipedia.org/wiki/Email_address#Syntax).

**Comment by oncletom** [comment]
This issue has been fixed by #284.

Feel free to create a new one to address more specific details about email addresses validation.
