### ISSUE TITLE
About: page title is missing

### ISSUE THREAD

**Issue by oncletom** [GFDRR/open-risk-data-dashboard#219]
Unlike other text-based pages, it lacks of a main title.

<img width="1163" alt="image" src="https://user-images.githubusercontent.com/138627/46664392-300bb380-cbc1-11e8-8cf4-e8f8f2fcd13f.png">

The expectation would be to add a `<h1>` which content would be `About this project` (or website).

**Comment by pzwsk** [comment]
Thanks, I would put "About this website"

**Comment by oncletom** [comment]
It has been successfully implemented by #251.

<img width="1149" alt="image" src="https://user-images.githubusercontent.com/138627/47099707-270c8900-d236-11e8-9a1f-05d9838c437f.png">
