### ISSUE TITLE
Country page: visually align and balance the metrics

### ISSUE THREAD

**Issue by oncletom** [GFDRR/open-risk-data-dashboard#228]
- [x] structure as a _definition list_ (`<dl>` / `<dt>` / `<dd>`)
- [x] on mobile: one metric = one row
- [x] on tablet: a combination which fits well the device width (1 metric = 1 row, 2 metrics = 1 row)
- [x] align margins with title and the table

<img width="942" alt="image" src="https://user-images.githubusercontent.com/138627/46666179-48320180-cbc6-11e8-9e94-4b138d410e42.png">

**Comment by pzwsk** [comment]
First column (Country Name) appears to be much larger than others on my screen.

![image](https://user-images.githubusercontent.com/2378439/47376831-f2944380-d6f3-11e8-86b2-28df87a7a7d8.png)

**Comment by oncletom** [comment]
Hello @pzwsk, this issue is about the metrics of a given country (eg: the Slovenia country page) and no the Countries list.

When we made the table responsive in #233, we flagged this issue, without creating a new one, my bad. This is due to later results being `United Kingdom of Great Britain and Northern Ireland`. We shall limit its width or make sure the country names wrap automatically in the column.

Can you create a new issue with your expectation of columns sizes? It would be super helpful.

**Comment by pzwsk** [comment]
While reviewing this, I found an issue with width of footer on country page https://dev.riskopendata.org/dataset_list.html?idcountry=SI&idcategory=0
