### ISSUE TITLE
Dataset page: put more emphasis on the dataset download

### ISSUE THREAD

**Issue by oncletom** [GFDRR/open-risk-data-dashboard#236]
At the moment, the dataset page provides a lot of informations about its metadata.
But accessing the dataset is actually lost within the page, like the 2 blue links on this screenshot:

![image](https://user-images.githubusercontent.com/138627/46670395-5c7bfb80-cbd2-11e8-9f76-230bdecfb98d.png)

Expectations to be worked out but maybe:

- a table of contents at the top (_à la_ Documentation page)
- a proper "Download" section (like "Metadata") with buttons-like links

**Comment by pzwsk** [comment]
Agree with issue. 

Links can point to direct download, dataset page, metadata, etc.

I would therefore name it something  like "Data links" (idea taken from data.gov.uk), rather than "Download"

**Comment by pzwsk** [comment]
I have had more thoughts on this.

The issue for now is that we do not record the access method of the data, i.e whether by direct download, API, or through a Web page. Putting a download button might confuse users if the landing url is a webservice or something else.

This shows the need for our database and the data we record to be more conformant with DCAT or Schema.org standard. 

For now, I will block this issue.
