### ISSUE TITLE
Dataset list - change tooltip values by answer instead of question

### ISSUE THREAD

**Issue by newick** [GFDRR/open-risk-data-dashboard#257]
<img width="1680" alt="capture d ecran 2018-10-17 a 14 34 07" src="https://user-images.githubusercontent.com/657454/47086470-d7b85f80-d219-11e8-8c35-85f237f9bf60.png">

**Comment by pzwsk** [comment]
+1

**Comment by oncletom** [comment]
@pzwsk you moved this one to "in progress", but is anybody working on it?
