### ISSUE TITLE
[performance] Explore locations: country score request takes 2.6sec to load

### ISSUE THREAD

**Issue by oncletom** [GFDRR/open-risk-data-dashboard#260]
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/138627/47104769-76f14d00-d242-11e8-8abb-cb7b11a03528.png">

**Comment by pzwsk** [comment]
Hi @nastasi-oq could you investigate when you have time, thanks

**Comment by pzwsk** [comment]
Hi @nastasi-oq not sure if you have time before christmas break but would be great if we can address this.

I am going to put in on your board.

**Comment by nastasi-oq** [comment]
> I suspect this problem is likely to vanish if the API returns the Open/Restricted/Closed/Unknown data instead of the scoring.

I agree with @oncletom , at least postpone the issue after the new scoring implementation.

**Comment by nastasi-oq** [comment]
![explore_countries](https://user-images.githubusercontent.com/1670278/52637532-bc134c00-2ecf-11e9-8273-503486ea594f.png)

**Comment by oncletom** [comment]
Yeah, problem solved on this one 👍
