### ISSUE TITLE
[favicon] it is not displayed on every pages

### ISSUE THREAD

**Issue by newick** [GFDRR/open-risk-data-dashboard#266]
On the homepage it's ok:
![image](https://user-images.githubusercontent.com/657454/47165439-40770900-d2fa-11e8-8ebf-78eb9786da90.png)

but for example on dataset list, there's nothing displayed:
![image](https://user-images.githubusercontent.com/657454/47165475-57b5f680-d2fa-11e8-9dd5-eb5e39f6ebfe.png)

**Comment by dedandy** [comment]
I'm fixing

**Comment by oncletom** [comment]
It has been addressed in #269 — next time it would be nice to address issues one by one.
