### ISSUE TITLE
Change open data column to a data visualization that shows the number out of 36.

### ISSUE THREAD

**Issue by gracedoherty** [GFDRR/open-risk-data-dashboard#271]
A simple horizontal fill bar like what is existing for the score would fit well with the existing layout. Could have it change color as it gets filled (e.g. from red to green).

**Comment by oncletom** [comment]
@gracedoherty @pzwsk what is the reasoning behind changing the color from red to green? I mean, do you have a gradient scale in mind?

I suspect a red/green gradien can be a bit punitive and different from the current red/green (off/on) scheme.

Can I offer to play on the intensity of green instead? From a faded green to full green (it's easier to play with percentages this way as well).

**Comment by oncletom** [comment]
Cool. I'll try something.

Otherwise, do you have a threshold in mind when the red background of the gauge should turn into green?

**Comment by gracedoherty** [comment]
Actually that's a good reason why faded to full green would be better, since we don't have a threshold for "good" for this indicator.
