### ISSUE TITLE
Fix data type icons color issue.

### ISSUE THREAD

**Issue by gracedoherty** [GFDRR/open-risk-data-dashboard#272]
The icons turn blue when you hover over them, but after a split second they return to red. Make them stay blue during hover.

**Comment by oncletom** [comment]
@gracedoherty which page are you referring to? On both https://dev.riskopendata.org/dataset_details.html?keyds=50 and https://dev.riskopendata.org/countries.html, the hovered data type icon is magnified but keeps the same colour.

If the problem happens on these pages, can you tell me which web browser did you encounter the problem with?

Thank you :-)

**Comment by gracedoherty** [comment]
Looks like it's only happening on Edge. It's on both Explore Locations and the country page. The icons turn blue briefly as they grow bigger, then the blue disappears.

I should make Chrome my primary browser to avoid these issues, but then I wouldn't notice the issues exist. ;)

**Comment by oncletom** [comment]
Thanks! I will have a look on Edge then :)

I was asking because I could not see the problem either on Firefox, Safari or Chrome so I was wondering if I were looking at the right place.

**Comment by oncletom** [comment]
I indeed reproduced the problem on Edge 15. On Edge 16 and above it does not appear.

I'm investigating a bit further to understand its cause.

**Comment by oncletom** [comment]
@gracedoherty as far as I can see, the problem has been solved. Reopen the issue if it persists on your side :-)
