### ISSUE TITLE
[performance] Dataset List: API call takes around 9 seconds to perform

### ISSUE THREAD

**Issue by oncletom** [GFDRR/open-risk-data-dashboard#280]
I was investigating how to compute the scores sketched #264 on the client-side, without having to do any work on the backend side.

It happens a call to https://index.opendri.org/api/dataset/ takes around 9 seconds to return results.

I don't know if it is an expected timing and if there are recommended strategies to work around this.

**Comment by pzwsk** [comment]
cc @nastasi-oq for discussion on this, thanks

**Comment by nastasi-oq** [comment]
Delegate client-side the calculation of scores prevent any further possibilities of caching strategies leading to unnecessary FE load. 

9 seconds are spent to calculate scores (current algorithm is quiet complex) and above all, the view had not been thought to be served without filters enabled.

**Comment by oncletom** [comment]
Well, it might not be performant by design and for good reasons but it is used as is nonetheless.

If the code or the API remains untouched, could we consider caching the output via nginx? It's [provided to us for free](https://www.nginx.com/resources/wiki/start/topics/examples/reverseproxycachingexample/) by the reverse proxy mechanism, and the scores don't change much during the day.

**Comment by pzwsk** [comment]
We may also simplify the algorithm through several ways as discussed with
OpenDRI team last monday:

* Remove complex scoring system and replace it by simple indicators (open,
restricted, closed, unknown);
* Take into account all dataset submissions, not only most open dataset
submission for each key dataset;
* Remove ThinkHazard! filter when countries have a low or very low level
and replace it by a visual indication of the TH level instead;

Those suggestions are to be further explained and validated but I believe
this would reduce CPU need when calculating indicators.

That being said, any other option, such as caching the output, might be
also considered.
The drawback is that contributors would not see their contribution
reflected immediately.

**Comment by nastasi-oq** [comment]
> We may also simplify the algorithm through several ways as discussed with OpenDRI team last monday: * Remove complex scoring system and replace it by simple indicators (open, restricted, closed, unknown); * Take into account all dataset submissions, not only most open dataset submission for each key dataset; * Remove ThinkHazard! filter when countries have a low or very low level and replace it by a visual indication of the TH level instead; Those suggestions are to be further explained and validated but I believe this would reduce CPU need when calculating indicators. That being said, any other option, such as caching the output, might be also considered. The drawback is that contributors would not see their contribution reflected immediately.

Remove complexity from scoring could reduce elaboration time quite a lot, moving filtering client side miss all the advantages of server side query caching, if data submission became not so frequent also use django cache and clean it when some modification happens to the data could be an option, expensive just the first time for each kind of query.

**Comment by nastasi-oq** [comment]
``dev.riskopendata.org`` is updated with the new scoring API, moving from 9000 to  ~300 ms.

**Comment by nastasi-oq** [comment]
Question: analyzing this query I found that just filtering by country improve by 1 order of magnitude the performances, is the raw version a good performances indicator yet ?
