### ISSUE TITLE
Remove from frontend side Angular $locationProvider framework

### ISSUE THREAD

**Issue by CIMAManuel** [GFDRR/open-risk-data-dashboard#285]
$LocationProvider is not use and we can remove it.
Before to do this we must check all href tags in all html pages and all dynamic link in JS files.
Moreover in JS files we use $location for identify pages and url parameters and we must to check if it is bound to $locationProvider framework.

**Comment by CIMAManuel** [comment]
Also we can remove "changeview" function from HREF tags in HTML file.
This function is not used.

**Comment by oncletom** [comment]
Addressed by #425
