### ISSUE TITLE
Revert to old logo

### ISSUE THREAD

**Issue by pzwsk** [GFDRR/open-risk-data-dashboard#293]

**Comment by dedandy** [comment]
Hy all

Now I'm approaching revert logo 

latest words around that from @gracedoherty:

_Text logo: "OpenDRI Index", where OpenDRI is blue and Index is muted orange.
Existing circle logo: change orange to muted orange, change red to blue.
Website: change anything red to muted orange. That shouldn't take long to do. Once we see how that looks, we can decide whether we need to change the existing blues to the true OpenDRI blue._

I'm going in this directtion?

**Comment by dedandy** [comment]
now simply revert latest version ;)
