### ISSUE TITLE
Country page: Reference of dataset under Key dataset name

### ISSUE THREAD

**Issue by pzwsk** [GFDRR/open-risk-data-dashboard#307]
Currently the column `Dataset` only provides with the name of the `Key dataset`.

Add a line under the Key dataset name with information (Dataset Title, Dataset Publisher (organization), Date of last update) related to the dataset actually assessed.

Please coordinate with @nastasi-oq on backend for dataset title.

Some remarks: 
- separate each field by a comma
- if field is empty, remove comma that comes just after
- if sentence exceeds length of the line, break it and put (...) in the end

Here is a preview

![image](https://user-images.githubusercontent.com/2378439/48225624-99880900-e39d-11e8-892f-4366a5ecef5f.png)

**Comment by pzwsk** [comment]
Hi @CIMAManuel could you have a look to this one and let me know if ok to implement?

Thanks!

**Comment by CIMAManuel** [comment]
Hi @pzwsk this change is possible but now server don't provide all informations.
I think we must to implement a different server response to do that.

For @nastasi-oq: API call 'country_scoring/' + countryID + CategoryFilters + ApplicabilityFilers'.

**Comment by pzwsk** [comment]
Ok, let's discuss with @nastasi-oq and @oncletom 

I would suggest to add in the response, 


name of the organization (does the dataset exist question)
date of last update (is the dataset up to date question)
additional info

also, would that be a lot to do add a field title in the database? if NO, I would appreciate we do it as well.

**Comment by oncletom** [comment]
I have opened #325 to discuss the required backend implementation changes.

I'm not aware of a performant way to retrieve the required data. I label the issue as `blocked` until a technical solution is found.

**Comment by pzwsk** [comment]
Also need to address #329

**Comment by CIMAManuel** [comment]
Is this issue blocked yet?

**Comment by oncletom** [comment]
So far my understanding is it is blocked on the frontend side while #325 is under development.

**Comment by oncletom** [comment]
Resolved by #363.

**Comment by pzwsk** [comment]
Here is what we have on dev. Seems we are using static parameters and not what is provided by API.

![image](https://user-images.githubusercontent.com/2378439/50004435-6e4d9680-ffa7-11e8-860a-850afa3fc6bb.png)

**Comment by oncletom** [comment]
@pzwsk, what do you mean by "we are using static parameters"?

**Comment by pzwsk** [comment]
On example I checked above, name of organization and date are not the right ones and are always the same.

Without having checked the code, I see  two possibilities:

- we are using name of organization of user instead of name of organization of dataset submitted 
AND we are using date of submission instead of date of last update;
- we are not using API response but static harcoded param;

**Comment by oncletom** [comment]
The rows are populated out of these data query: https://dev.riskopendata.org/api/country_scoring/AU

It looks like production data are pretty much different: https://index.opendri.org/api/country_scoring/AU

**Comment by oncletom** [comment]
It's a discussion to have in #362 or #352 then, to adjust what data are provided by the backend.

**Comment by oncletom** [comment]
Solved with #366.

**Comment by pzwsk** [comment]
Reopening this one.

One of the instructions has not been addressed:
> if sentence exceeds length of the line, break it and put (...) in the end
