### ISSUE TITLE
Frontend installed on development machine stop to use development backend.

### ISSUE THREAD

**Issue by nastasi-oq** [GFDRR/open-risk-data-dashboard#311]
@pzwsk @CIMAManuel @oncletom @nastasi-oq 
Currently frontend installed on https://dev.riskopendata.org is using production backend API.

- is used production DB to perform any kind of tests (creating temporarily inconsistencies and having obvious limitation on kinds of tests that could be performed)
- there is no more the possibility to test integration between pre-production FE and pre-production BE in a shared way.

**Comment by oncletom** [comment]
So if I understand well, the expectation is to plug `dev.riskopendata.org` to the pre-production back-end, right?

I would then be interested by #263 being merged as it streamline the API endpoint to `/api/` for both production and pre-production.

By doing so, the frontend can be deployed the same way for production and pre-production, and the API datasource responsability is setup on the nginx side of things.

Would that be a good option for you?

**Comment by nastasi-oq** [comment]
> So if I understand well, the expectation is to plug dev.riskopendata.org to the pre-production back-end, right?

Right.

> I would then be interested by #263 being merged as it streamline the API endpoint to /api/ for both production and pre-production.

Change the API endpoint to ``/api/`` is just matter of configuration for django and nginx, no problem.

> By doing so, the frontend can be deployed the same way for production and pre-production, and the API datasource responsability is setup on the nginx side of things.
> 
> Would that be a good option for you?

Yes, would be good, in the previous configuration production and development was on the same machine so we had some limitation, now that are 2 different things are simpler.

@oncletom I'm going to add some changes to this PR to align it with your proposal.
