### ISSUE TITLE
Dataset details page: New page layout

### ISSUE THREAD

**Issue by pzwsk** [GFDRR/open-risk-data-dashboard#340]
Modify general layout of dataset details pages following screenshots below.

The main objective is to clearly separate information on `What dataset is expected` from information on the actual `Submission`, what is evaluated.

The secondary objective is to provide more explanation on the open data evaluation of the dataset.
This is further explained in issue #343

The third objective is to enable users to see alternative datasets at global or country level (submissions for same dataset and same country or for same dataset and world that may be used as an alternative of this dataset). This is further explained in #341

Page by default (not expanded) 

![image](https://user-images.githubusercontent.com/2378439/49429297-7556f680-f7a8-11e8-8713-2ffa29639af9.png)

Page with open data criteria visible

![image](https://user-images.githubusercontent.com/2378439/49433909-5447d300-f7b3-11e8-8e26-8631e00cf115.png)

**Comment by oncletom** [comment]
A few precisions based on today's call:

- when `More info` is clicked, there are more informations to display (to be defined)
- when `See details why` is clicked, the open data criteria are displayed
- there are 4 status sentences to display based on the criteria (`This dataset is free to access, use and share` is displayed when data is openly licensed, free, machine readable (?))

**Comment by pzwsk** [comment]
Here are sentences for `Is this dataset open data?` depending on status:

**Status conditions:** AT LEAST YES for ALL criteria EXCEPT Up to date
Yes, this dataset is free to access, use, and share*
(*) Some conditions may still apply

Logo: Open Data


**Status conditions:** YES for Data exists and is publicly available and NO for at least another EXCEPT Up to date

No, this dataset has technical or legal restrictions on access, use and share

Logo: RESTRICTED (as text for now)

**Status conditions:** YES for ALL Data exists and NO for others

No, this dataset exists but is not available

Logo: CLOSED (as text for now)

**Status conditions:** No data

No, the status for this dataset is unknown

Logo: UNKNOWN

**Comment by pzwsk** [comment]
See revised version of screenshot for collapsed version, with Alternative datasets added.

I would breakdown issues this way:

* New general layout for dataset detail page
* Box: Is this dataset open data?
* Box: Alternative datasets
* Box: More info (this one will need some work on BE so will probably keep it for another iteration)

@gracedoherty could you have a look and let us know what you think, in particular on terms?

Thanks!

**Comment by pzwsk** [comment]
Below is expanded version:

![image](https://user-images.githubusercontent.com/2378439/49429119-04afda00-f7a8-11e8-8c31-6dcbb8faad12.png)

**Comment by pzwsk** [comment]
> 
> 
> A few precisions based on today's call:
> 
>     * when `More info` is clicked, there are more informations to display (to be defined)
> 
>     * when `See details why` is clicked, the open data criteria are displayed
> 
>     * there are 4 status sentences to display based on the criteria (`This dataset is free to access, use and share` is displayed when data is openly licensed, free, machine readable (?))

I have added more details at the top of the issue.

I am suggesting to block the `more info` for now as this will require two additional fields or more in the db (Why is this dataset important? Data attributes).

**Comment by pzwsk** [comment]
Some more clarifications:

- When no dataset title, put `Untitled`

**Comment by gracedoherty** [comment]
I think this precision is great. Some comments:

- **What dataset is expected?** can be **Category definition**. This is where I prefer that the term "dataset" refer to an actual file (e.g. Defra's Marine DEM), and "category" to define the group under which Defra and other DEMs fall under ("DEM"). We should change the Base Data/Hazard/etc. term to **Classification** or **Class**.

- **Show more details** and **Show less details** in the Open Data section can be shortened to **See details** and **Less details**.

- I don't know where you are referring to when you say "More details" button.

- Shorten to **Is this dataset open?**

- Shorten to **(*) Restrictions may apply.**

**Comment by pzwsk** [comment]
Thanks @gracedoherty,

Point 1: My suggestion is to use dataset for both and differentiate between dataset that is expected (key dataset) and dataset that is submitted (submission). The concept of key or high value dataset is now being recognized and used by various groups such as G8, Open Data Charter and now EU Commission who wants to define a list of high value datasets in its next Directive. To me category is broader and looks more like the term data theme used by UN-GGIM. In that case, it is very broad categories. But let's continue the discussion also in light of user tests.

Point 2: OK

Point 3: If you refer to "More info" it was on a previous version of the screenshot that I removed

Point 4: OK

Thanks!

**Comment by pzwsk** [comment]
Hi, I just merged #370 

There are some subtleties that I would like to address (Approved button, size of Dataset title) but very good job so far.

**Comment by pzwsk** [comment]
Hi, going to move this to iteration #6 as #341 and #343 are still todo/ongoing.

**Comment by oncletom** [comment]
This one will be good to go as #405 is merged.
