### ISSUE TITLE
Dataset details - Title in submit page 

### ISSUE THREAD

**Issue by CIMAManuel** [GFDRR/open-risk-data-dashboard#354]
Add title control for submit page

**Comment by CIMAManuel** [comment]
@pzwsk can the field be in the Dataset section before country selection? Or we can add the field in the "Additional information".

**Comment by CIMAManuel** [comment]
@pzwsk we can add a litle description under the label "Title". Do you have somenthing to suggest?
Thanks

**Comment by oncletom** [comment]
Resolved by #360.
