### ISSUE TITLE
Update Dataset - title check

### ISSUE THREAD

**Issue by CIMAManuel** [GFDRR/open-risk-data-dashboard#364]
If title is "null" the check function doesn't check the field.

**Comment by oncletom** [comment]
Well, wasn't the title supposed to be optional?

**Comment by CIMAManuel** [comment]
I understand that field must be mandatory.

**Comment by pzwsk** [comment]
My mistake, we discussed it on Monday but it was not written in the related issue.

Title field should be optional indeed as there can be few cases where there is no dataset title (dataset does not exist, dataset do exist but with no clear or known title).

**Comment by CIMAManuel** [comment]
Ok, so we must to delete title's check in service.js file. If you agree I can use this branch to remove it.

**Comment by pzwsk** [comment]
Ok yes I agree
