### ISSUE TITLE
Deploy Iteration 5 before Christmas Holidays.

### ISSUE THREAD

**Issue by pzwsk** [GFDRR/open-risk-data-dashboard#372]
And/Or after #340 has been fully deployed on Dev

**Comment by oncletom** [comment]
Deploy is doable whenever backend API v2.1.0 is deployed in production.

We should not wait for an issue to deploy, unless a bug is blocking the usage of the website. We can redeploy the frontend as many times as we want.

**Comment by pzwsk** [comment]
Ok, agree, thanks,

I am blocking this until backend is deployed then.

cc @nastasi-oq

**Comment by pzwsk** [comment]
Version 2.1.0 of API has been deployed.

Ok for me to deploy current version of dev on prod. 
@oncletom can you do it?

This will allow team to review and add titles.

Best

**Comment by oncletom** [comment]
It's done, with the tag [`fe_20181221`](https://github.com/GFDRR/open-risk-data-dashboard/releases) 👍
