### ISSUE TITLE
Missing legend for colors of criteria icons

### ISSUE THREAD

**Issue by cgiovando** [GFDRR/open-risk-data-dashboard#387]
The colors (green and maroon) of criteria icons in summary pages are not obvious. I know that they indicate whether the criterion is satisfied or not, but maybe we could make it more obvious to the first-time user through a legend or tooltip on mouseover?

![screen shot 2019-01-11 at 12 04 57](https://user-images.githubusercontent.com/10201533/51030499-e785dc80-1599-11e9-9f75-c6b5cb1775dc.jpg)

The current tooltip message is the same on green and maroon icons, but maybe could be extended to dynamically answer YES/NO when the criterion is satisfied or not?

**Comment by pzwsk** [comment]
Thanks, this issue has been mentioned already and should be implemented in next iteration. See #257 

Closing this one
