### ISSUE TITLE
Submitting multiple datasets for each type

### ISSUE THREAD

**Issue by cgiovando** [GFDRR/open-risk-data-dashboard#389]
Wondering whether is possible and how to handle multiple submissions within the same category? 

For example for _Digital elevation model_ in addition to the current global [SRTM dataset](https://index.opendri.org/dataset_details.html?keyds=529), it could be possible to include the [ASTER GDEM](https://asterweb.jpl.nasa.gov/gdem.asp), which has similar resolution and coverage.

**Comment by pzwsk** [comment]
Thanks, how to show multiple or alternative datasets for same key dataset is currently discussed here #305 and here #340 

That being said, you can already submit more than one datasets for same key dataset but until now we only consider most open version in the scoring.

**Comment by pzwsk** [comment]
Closing this one, now implemented.
