### ISSUE TITLE
Explore Countries: Show all dataset submissions for a key dataset

### ISSUE THREAD

**Issue by pzwsk** [GFDRR/open-risk-data-dashboard#391]
Hi,

currently, https://index.opendri.org/countries.html and https://index.opendri.org/dataset_list.html only consider the most open dataset per key dataset.

The result is that alternative datasets (other submissions for similare key datasets) are not visible on dataset_list and not taken into account in scoring and total number of datasets.

The aim is to review this as part of #305 but I was wondering if - as a 1st step - we could remove this condition and consider/show all datasets submissions on countries.html and dataset_list.html ?

**Comment by pzwsk** [comment]
cc @nastasi-oq

**Comment by nastasi-oq** [comment]
@pzwsk I think it is possible, just the visualization or we want to change the current scoring method ?

**Comment by pzwsk** [comment]
Priority is visualization, we will address country score trough #305 

Here is the proposal:

![image](https://user-images.githubusercontent.com/2378439/51183734-6f3d5500-18d2-11e9-93d0-e6b6b9f7f20e.png)

**Comment by pzwsk** [comment]
Hi @nastasi-oq I put in Backend iteration #6 

Please consider this priority.

Best

**Comment by oncletom** [comment]
This one seems to be addressed, and there is no need to change anything on the frontend side.
