### ISSUE TITLE
Explore countries: remove category and hazard filter until solution is found.

### ISSUE THREAD

**Issue by pzwsk** [GFDRR/open-risk-data-dashboard#419]
1. With new API, category and hazard filters do not work for `Explore Countries` page currently
2. User interviews show that those filters are not clear, especially for `Explore Countries` page
3. A new set of open data indicators is going to replace scoring system

Suggestion is to remove category and hazard filters until a better UX/UI working with new set of open data indicators is found.

**Comment by oncletom** [comment]
On the `dataset_list.html` page, the filter could be moved below the "Show: Submitted, Not Submitted, All" filters, and be given a similar look with their  number of datasets (it can be developed in a new issue if that's relevant).
