### ISSUE TITLE
Dataset List: group alternative datasets by key dataset

### ISSUE THREAD

**Issue by pzwsk** [GFDRR/open-risk-data-dashboard#421]
Following request from @vdeparday 

Here this a proposal to show similar (alternative datasets) for same key dataset on the Country page:

![image](https://user-images.githubusercontent.com/2378439/52137601-3b408e80-264b-11e9-9e51-c00a35d4678e.png)

Level 1:
Key datasets are sorted either by name or (if possible) by most open dataset.

Level 2:
Within key dataset group, dataset are sorted by most open to less open.

**Comment by pzwsk** [comment]
Hi @oncletom as discussed could you have a look next week?

Thanks!

**Comment by vdeparday** [comment]
Definitely a high priority, will look very good on the Global Dataset Page. Seeing all the global dataset in one page is something a lot of people have been wanting for a while !

The layout looks pretty clean. Maybe we can also have a clean way of having title, source, date aligned (but maybe that would be more ugly), to try out.
