### ISSUE TITLE
Submit dataset page: after sumitting a dataset, data links stay on the new blank submit page

### ISSUE THREAD

**Issue by pzwsk** [GFDRR/open-risk-data-dashboard#429]
When a user click on submit button, he is redirected to a new blank submit dataset page without any data links in it.

**Comment by pzwsk** [comment]
Hi @CIMAManuel can you have a look to that one? Thanks

**Comment by CIMAManuel** [comment]
@pzwsk  What do you expect?

**Comment by pzwsk** [comment]
See new description above.

**Comment by oncletom** [comment]
Fixed by #454
