### ISSUE TITLE
Review registration messages

### ISSUE THREAD

**Issue by pzwsk** [GFDRR/open-risk-data-dashboard#44]
- [x] 1. On register page, when clicking on Send request, the message should be clearer, something like: Registration confirmation sent to [email]. Please check your mailbox.

- [x] 2. Please modify the content of the registration confirmation email with the following text: "Thanks for your request to register to the Open Data for Resilience Index. Please confirm your registration by clicking on the button below. "

- [x] 3. Registration confirmed page: Remove "Registration complete correctly!" instead: "Thanks, you can now complete your profile or submit a dataset" with appropriate links.

**Comment by nastasi-oq** [comment]
Point 2 closed with https://github.com/GFDRR/open-risk-data-dashboard/pull/64

**Comment by nastasi-oq** [comment]
Point 2: 'dev' backend updated.

**Comment by nastasi-oq** [comment]
Point 2: 'dev' backend updated. (@CIMAManuel)
