### ISSUE TITLE
Submit dataset - Edit it's own submission

### ISSUE THREAD

**Issue by pzwsk** [GFDRR/open-risk-data-dashboard#45]
It should be possible for a contributor to edit it's own submissions before validation by reviewer.

**Comment by CIMAManuel** [comment]
The contributor can edit own dataset before validation but there was a 
compatibility problem with Safari & Firefox browser.
Please delete your browser cache and test again.
Thks

**Comment by pzwsk** [comment]
Ok thanks, got it.
