### ISSUE TITLE
Explore countries page : stacked progress bar with 4 indicators

### ISSUE THREAD

**Issue by pzwsk** [GFDRR/open-risk-data-dashboard#463]
Currently `Unknown` indicator (the number of key datasets without any submission) is showed apart from the other indicators in a specific progress bar. The suggestion is to combine it with other indicators `Open`, `Restricted`, `Closed` into one single progress bar.

Suggestion : 

- For each country, the combination (addition) of the number of datasets for each of the 4 indicators represents 100%
- The number indicates the number of dataset for each indicator
- It is possible to sort countries depending on each number of datasets per indicator

![image](https://user-images.githubusercontent.com/2378439/54022912-e3d69680-4193-11e9-9825-066b39555165.png)

**Comment by vdeparday** [comment]
This one looks really good and clear, except of "unknown" could we say
"missing" , because otherwise it may sound that we have the dataset but it
is just the status, closed, open, restricted that is unknown.

**Comment by pzwsk** [comment]
Sorted by number of open data

![image](https://user-images.githubusercontent.com/2378439/54214817-37741780-44e7-11e9-93d8-49ac5d390670.png)

**Comment by pzwsk** [comment]
Sorted by number of missing datasets

![image](https://user-images.githubusercontent.com/2378439/54214881-4ce94180-44e7-11e9-84cf-589ef46be912.png)
