### ISSUE TITLE
Add How to deploy in Readme file

### ISSUE THREAD

**Issue by pzwsk** [GFDRR/open-risk-data-dashboard#464]
Hi @oncletom could you add one or two line in Readme to explain workflow on how to deploy from GH on production, as you just did? Thanks!

**Comment by pzwsk** [comment]
I found how to do it and added explanation at the end of the Readme file here https://github.com/GFDRR/open-risk-data-dashboard/blob/master/frontend/README.md

Can you have a look and add any additional useful info? Many thanks

**Comment by oncletom** [comment]
I added a few more informations to complete what you accurately wrote.
