### ISSUE TITLE
Replace indicator "Unknown" by "Missing"

### ISSUE THREAD

**Issue by pzwsk** [GFDRR/open-risk-data-dashboard#469]
![image](https://user-images.githubusercontent.com/2378439/54610401-3e55d980-4a55-11e9-9195-174955d1893b.png)

- [x] Country page
- [x] Documentation page

**Comment by vdeparday** [comment]
Could we have it on the homepage too? Maybe below the other three? and with a call to action to contribute?

**Comment by pzwsk** [comment]
Hi @vdeparday have a look to #470 and let me know what you prefer
