### ISSUE TITLE
Login - Forgot your password?

### ISSUE THREAD

**Issue by pzwsk** [GFDRR/open-risk-data-dashboard#47]
Add a forgot your password feature on the login page.

**Comment by CIMAManuel** [comment]
I need a BE API.

**Comment by nastasi-oq** [comment]
BE - functionality is included in https://github.com/GFDRR/open-risk-data-dashboard/pull/62

**Comment by nastasi-oq** [comment]
BE - version with the new functionality installed on 'dev'.
