### ISSUE TITLE
Fix behavior of clicking on icons on each country page

### ISSUE THREAD

**Issue by cgiovando** [GFDRR/open-risk-data-dashboard#51]
This is either a bug or it's not clear to me how numbers in `Dataset instances` and `Missing Datasets` change when the user starts clicking on each of the data and hazard type icons.

Also, if clicking once means `selected` and clicking again means `not selected` it should be made more clear than just changing color from red to blue.

**Comment by pzwsk** [comment]
See new version https://dev.riskopendata.org/dataset_list.html?idcountry=AU&idcategory=0
