### ISSUE TITLE
Get the data

### ISSUE THREAD

**Issue by pzwsk** [GFDRR/open-risk-data-dashboard#65]
Add a data export feature so that users can download all datasets entries as a spreadsheet (csv preferred) in one bulk download. Data download link may be added in the countries view.

**Comment by nastasi-oq** [comment]
BACKEND: a PR is opened here: https://github.com/GFDRR/open-risk-data-dashboard/pull/70
At `/datasets_dump`any registered user can download all datasets in csv format.
Tags list is dumped as a concatenation of  ` | ` separated strings.
Urls list is dumped as a concatenation of ` | ` separated urlencoded strings.
Currently all Dataset model fields are dumped, the list is here: https://github.com/GFDRR/open-risk-data-dashboard/blob/csv-export/backend/ordd_api/views.py#L806
About the "addition": could you open a new issue about it ?

**Comment by CIMAManuel** [comment]
Frontend ok, link in the footer

**Comment by pzwsk** [comment]
Tested ok on 
* IE 
* Chrome

Not working on Firefox

**Comment by nastasi-oq** [comment]
Missing deploiment step, fixed.
Please retry.
