### ISSUE TITLE
Homepage

### ISSUE THREAD

**Issue by pzwsk** [GFDRR/open-risk-data-dashboard#66]
* Clear distinction between header and main content of the homepage
* Big title: Tracking and improving Open Data for Resilience worldwide
* Show icons and labels such as on ThinkHazard! or Country View
* Add those indicators: XX datasets submitted | YY percent open | ZZ countries covered. Move other indicators to a specific page.
* Buttons: Explore countries | Submit new dataset

**Comment by pzwsk** [comment]
Here is a review of the issues based on last version of the homepage Sep 29.

* Picture is nice but should be free of rights (openly licensed or in public domain)? Also, please change the height size so that we can see the whole picture on most of the screens.
* Title should stay at the top, within the picture box, not below. Please also rewrite as: "Tracking open disaster risk data worldwide" so that it fits on one line only
* Icons: might be better to have icons not transparent. Can be difficult to see them otherwise. Also, we need to add captions, flood, earthquake, etc.
* Indicators: please correct with right terms as the figures are now displayed above: Datasets submitted | Countries covered | Datasets open. Also, is it possible to place the figures at the center of the circles?
* Add two buttons: Explore countries (linking to countries page) AND Submit a dataset (linking to submit new dataset page) below those indicators.
* Please remove the white part with the 3 boxes
* Please refine the footer with something like opendri.org or understandrisk.org footer

**Comment by pzwsk** [comment]
Issue on Firefox browser
![image](https://user-images.githubusercontent.com/2378439/31118442-b1e2828e-a82d-11e7-96bf-3c41709ff655.png)

**Comment by pzwsk** [comment]
- [ ] Ensure picture is free of rights and provide source (credit).
- [ ] Improve contrast between picture and title and increase title sized.
- [ ] Remove zooming effect on picture.
- [ ] Reduce size of text below indicators.
- [ ] Add names below hazard icons, such as on ThinkHazard! and reduce size of icons.
- [ ] Remove statistics button.
- [ ] Statistics and download links only in the footer and available for all users, not only registered ones.

**Comment by pzwsk** [comment]
There is still differences of font sizes and layout for the home page between web explorers.

Chromium (Ubuntu)
![image](https://user-images.githubusercontent.com/2378439/31535896-0b1a7aec-affd-11e7-9963-54a716e91662.png)

Firefox (Ubuntu)
![image](https://user-images.githubusercontent.com/2378439/31535950-3e7d5e68-affd-11e7-8d1e-5c5fe683b2b3.png)

**Comment by pzwsk** [comment]
There are still CSS differences between FF and other web browsers on homepage. Will close this issue when fixed.

**Comment by CIMAManuel** [comment]
done
