### ISSUE TITLE
New version of key datasets

### ISSUE THREAD

**Issue by pzwsk** [GFDRR/open-risk-data-dashboard#71]
New version of key datasets is currently under revision by Andreas. Please wait for green light from him before applying changes to backend.

**Comment by nastasi-oq** [comment]
PR Opened at:
https://github.com/GFDRR/open-risk-data-dashboard/pull/77

**Comment by pzwsk** [comment]
tested integration on https://dev.riskopendata.org

On submit dataset page (contribute.html) the 3 levels description are still available. The requirement is to only have national level.

**Comment by pzwsk** [comment]
Relevant to discussion above, need to add filter (national level only) on following FE pages (please check if no other page/feature is missing):

- [ ] contribute.html (description)
- [ ] dataset_list.html (list of dataset)
- [ ] countries.html (score)
- [ ] index.html (indicators)
- [ ] stats.html

cc @nastasi-oq @CIMAManuel

**Comment by nastasi-oq** [comment]
@pzwsk please, open a specific new issue for national-only keydataset.
