### ISSUE TITLE
Contribute page - Dataset description should not be an entry field

### ISSUE THREAD

**Issue by pzwsk** [GFDRR/open-risk-data-dashboard#8]
"Dataset Description" is not an entry field but a text which depends on the selected "Dataset" AND "Scale".
It is suggested to add the description in a text box below the dataset name that will change depending on the "Dataset" and "Scale".

**Comment by daniviga** [comment]
The API model is already like this. For example these are all the descriptions in the `Earthquake` dataset https://riskopendata.org/api-dev/keydataset/2/0/26/ and this is the `earthquake catalogue` object https://riskopendata.org/api-dev/keydataset/2/0/26/39

**Comment by pzwsk** [comment]
Final consensus is that when selecting `country` and `dataset`, description of dataset should be per default the one for `scale `(level of applicability) = `national`. The contributor would then have the possibility to select another definition / level of applicability.
