### ISSUE TITLE
Notify reviewers when new dataset submitted

### ISSUE THREAD

**Issue by pzwsk** [GFDRR/open-risk-data-dashboard#80]
Send an email to all reviewers when a new dataset is submitted with link to the dataset to review.

**Comment by nastasi-oq** [comment]
@pzwsk, currently we have 6 different notifications to admin email only:

| Notification | Site Administrator | Admin users | Reviewer users |
|---|:---:|:---:|:---:|
| New user activation | Yes | | | 
| User deletion | Yes | | |
| New comment | Yes | | |
| Dataset creation | Yes | | | 
| Dataset update | Yes | | |
| Dataset deletion by owner | Yes | | |

The new schema will be:

| Notification | Site Administrator | Admin users | Reviewer users |
|---|:---:|:---:|:---:|
| New user activation | | Yes | | 
| User deletion | | Yes | |
| New comment | | | Yes |
| Dataset creation | | | Yes | 
| Dataset update | | | Yes |
| Dataset deletion by owner | | | Yes |

Please confirm these.

**Comment by pzwsk** [comment]
Perfect, thanks
