### ISSUE TITLE
FE - National level only filter

### ISSUE THREAD

**Issue by pzwsk** [GFDRR/open-risk-data-dashboard#83]
Relevant to discussion related to issue #71, please add filter (national level only) on following FE pages (please check if no other page/feature is missing):

- [x]  contribute.html (description)
- [ ]  dataset_list.html (list of dataset)
- [x]  countries.html (score)
- [x]  index.html (indicators)
- [x]  stats.html

cc @nastasi-oq @CIMAManuel

**Comment by nastasi-oq** [comment]
I created a branch that add (partially at this moment) the feature:
  https://github.com/GFDRR/open-risk-data-dashboard/tree/be_national-only

**Open Issues**:
- server side ad hoc checks
  - insert of new dataset is limited by FE to national level only: is enough or we must check also server side that new inserted dataset are at national level ?
  - make sense that users or reviewers cannot see already not national datasets ?
  - we must force download of national only datasets or is enough if we apply level filter also on these ?

**API Changes**:
- a get parameter "level=national" must be added to:
  - api/scoring_category/
  - api/scoring/(?P<country_id>[A-Z0-9][A-Z0-9])
  - api/scoring/
  - api/dataset/
  - api/dataset/(?P<pk>[0-9]+)
  - api/profile/dataset/
  - api/profile/dataset/(?P<pk>[0-9]+)

**Comment by pzwsk** [comment]
Dear @nastasi-oq @CIMAManuel can you give an update on this issue? Thanks!

**Comment by nastasi-oq** [comment]
Hi @pzwsk, this issue is blocked waiting for answers to the questions in our comment of Oct 18.
Could you please provide your input?

**Comment by pzwsk** [comment]
insert of new dataset is limited by FE to national level only: is enough or we must check also server side that new inserted dataset are at national level ?

**Only FE is ok.**

make sense that users or reviewers cannot see already inserted not national datasets ?

**YES**

we must force download of national only datasets or is enough if we apply level filter also on these ?

**When clicking on download, one should only get national level datasets**

**Comment by nastasi-oq** [comment]
(BE ✔, FE todo) [be_national-only branch](https://github.com/GFDRR/open-risk-data-dashboard/tree/be_national-only) allows it on BE side
All `Dataset`s and `KeyDataset`s are filtered before any operation, the only view that still needs level explicit is `/keydataset` for consistency (that is used just by FE internals).

**Comment by CIMAManuel** [comment]
FE: set National filter in new Dataset & Update Dataset. (dev.risk.. & www.risk)

**Comment by pzwsk** [comment]
Any update on this one? Thanks

**Comment by nastasi-oq** [comment]
@pzwsk  for me is completed, @CIMAManuel  ?
