### ISSUE TITLE
Several rendering and layout issue in IE 11 (default version on WB computers)

### ISSUE THREAD

**Issue by vdeparday** [GFDRR/open-risk-data-dashboard#87]
![image](https://user-images.githubusercontent.com/1036189/33402667-4434ef6c-d52b-11e7-8041-51e10b80a4c3.png)

![image](https://user-images.githubusercontent.com/1036189/33402673-4da58930-d52b-11e7-8e2e-daff271ddaf0.png)

![image](https://user-images.githubusercontent.com/1036189/33402688-5a7a0348-d52b-11e7-9907-a1f07c48c883.png)

**Comment by vdeparday** [comment]
This should be high priority as the default navigator in the WB is IE 11

**Comment by pzwsk** [comment]
I am also experiencing same issue for home page (missing figures in circles) with Chrome 62 and Firefox 57 on windows 10. 

Please @CIMAManuel, as mentionned by @vdeparday, could you have a look rapidly as we are ongoing internal testings with WB, including senior management.

Thanks

**Comment by pzwsk** [comment]
* Figures in circles on home seems to work ok now but takes a lot of time to load.
* However, I still have issues for country pages on Edge browser. See below.

![image](https://user-images.githubusercontent.com/2378439/34567503-db64cc6a-f162-11e7-8bec-c55358df8a52.png)
