### ISSUE TITLE
Review and simplify openness scoring methodology

### ISSUE THREAD

**Issue by pzwsk** [GFDRR/open-risk-data-dashboard#89]
#Openness scoring is very confusing for users and needs to be reviewed.

Some suggestion below to discuss below:
* Remove weight relative to datasets and depending on hazards and risk data categories as it is too confusing (Final report: 4.4.2 Data category scoring);
* Use a simple calculation methodology. e.g SUM (for each datasets openness)/ Number of datasets to consider;
* Decide what to do for datasets with more than one valid submission;
* Better communicate on new scoring methodology through homepage, countries, country, methodology and submit dataset pages;

**Comment by pzwsk** [comment]
Hi @nastasi-oq can you please point to code where dataset and country scores are calculated?

**Comment by nastasi-oq** [comment]
@pzwsk currently the "candidate" master for backend is the branch `thinkhazard180302` (not yet reviewed).
for the static part you can find code at: https://github.com/GFDRR/open-risk-data-dashboard/blob/thinkhazard180302/backend/ordd_api/models.py#L322
for the dynamic part you can find a couple of entry points here: https://github.com/GFDRR/open-risk-data-dashboard/blob/84f6c710b0efa9a19490657f9f1da8c2fb30f0f9/backend/ordd_api/views.py#L981
and here: https://github.com/GFDRR/open-risk-data-dashboard/blob/84f6c710b0efa9a19490657f9f1da8c2fb30f0f9/backend/ordd_api/views.py#L1001
and following where these functions are called (not so simple but the current score algorithm isn't simple).

**Comment by nastasi-oq** [comment]
Manage this issue require time and stability for the rest of the code, that doesn't the current scenario.

**Comment by pzwsk** [comment]
Can you clarify on what is implemented and what is not? Thanks

**Comment by pzwsk** [comment]
For instance, I see in code for statics part that new weights for open data criteria are not implemented.

    Does the data exist? +5 if YES
    Is the data available in digital form? +5 if YES
    Is the data publicly available? +5 if YES
    Is the data available online? +5 if YES
    Is the metadata available online? +5 if YES
    Is the data available in bulk? +10 if YES
    Is the data machine-readable? + 15 if YES
    Is the data available for free? + 5 if YES
    Is the data openly licensed? + 15 if YES
    Is the data provided on a timely and up to date basis? + 5 if YES

**Comment by nastasi-oq** [comment]
This is trivial to adjust but is just part of the simplification.
@pzwsk question: the maximum score for a dataset must be still 100 ? 
so the formula became (sum / 75.0 ) * 100.0

**Comment by pzwsk** [comment]
You are right, there is an issue with new criteria weights.
Let's keep it as it is for now and I will update documentation accordingly.
