### ISSUE TITLE
Change generic font

### ISSUE THREAD

**Issue by pzwsk** [GFDRR/open-risk-data-dashboard#90]
Change generic text font to Unit.

**Comment by pzwsk** [comment]
Font Unit is only available for a fee but we have a license for OpenDRI websites, I asked our colleagues to share it with us. Will let you know. Best

**Comment by pzwsk** [comment]
Fonts provided in .ttf format.

**Comment by CIMAManuel** [comment]
New font loaded in dev.riskopendata.org and www.riskopendata.org (and GitHub)

**Comment by pzwsk** [comment]
Ok, does not look better, I don't understand why my colleagues want to use this one ...

I checked and OpenDRI.org has font-family: "Helvetica Neue", Helvetica, Arial, sans-serif as paremeter for generic body font. 

Can you change to this font family? 
Thanks and sorry.
